support coredns v1.11.0
coredns/corefile-migration pull request #76
Opened 2023-08-09 10:27 UTC by tukwila

Now coredns release new version: https://github.com/coredns/coredns/releases/tag/v1.11.0, so do upgrade in corefile-migration.
And some plugin changes please review if it is right in versions.go?
@chrisohaver @miekg

<img width="592" alt="image" src="https://github.com/coredns/corefile-migration/assets/13757056/2489104f-9b50-4a5e-bc48-eb5deff1df4f">

2023-08-11 01:00 UTC, tukwila commented
@chrisohaver Could you please review this PR?

2023-08-13 14:23 UTC, tukwila commented
> The plugins map is not correct. It adds plugins that are not supported by the migration, and is missing plugins that it does support. If any new options have been added to supported plugins, those will need to be added.

Do you mean i need not to add any plugins currently? so i modify plugin definition like this,
<img width="533" alt="image" src="https://github.com/coredns/corefile-migration/assets/13757056/b3b34610-6991-485c-8609-d7b7d26bbf61">
Am i right?

2023-08-13 14:35 UTC, chrisohaver commented
I don’t know how to interpret your marked up screen shot. Please take a look at some of the prior PRs in this repo that have added a support for a new coredns version to see how they are done.

Please look at the release notes for the list of plugins the migration package supports. I would not recommend adding to that list at this time.

2023-08-14 13:04 UTC, tukwila commented
> I don’t know how to interpret your marked up screen shot. Please take a look at some of the prior PRs in this repo that have added a support for a new coredns version to see how they are done.
> 
> Please look at the release notes for the list of plugins the migration package supports. I would not recommend adding to that list at this time.

Yes, i read  prior plugins and coredns release-notes, then append plugins_1_11_0 cause's in v1.11.0 release-notes there are two new function added into plugins:
plugin/dnstap: add tls support (https://github.com/coredns/coredns/pull/5917)
plugin/k8s_external: add fallthrough option (https://github.com/coredns/coredns/pull/5959)

so, please review my code again. Big thanks.

2023-08-14 13:13 UTC, chrisohaver requested changes

2023-08-14 13:13 UTC, chrisohaver commented on migration/versions.go
> +	"dnstap":  		plugins["dnstap"]["v1"], // add tls support
_dnstap_ is not supported by the migration package at this time.

If you want to add support for it, you'll need to identify in which version of coredns it was introduced, and retroactively add support for all version migrations though 1.11.0.

2023-08-14 13:13 UTC, chrisohaver commented on migration/versions.go
> +	"k8s_external": plugins["k8s_external"]["v2"], //add fallthrough option
`plugins["k8s_external"]["v2"]` doesn't exist.  You need to add it to `plugins.go`

2023-08-14 13:13 UTC, chrisohaver commented on migration/versions.go
> +	"rewrite":      plugins["rewrite"]["v2"],
_rewrite_ had a new option added to it: https://github.com/coredns/coredns/pull/6004

2023-08-18 13:28 UTC, chrisohaver requested changes
Thanks! Looks good! Just some minor changes requested on comments.

2023-08-18 13:28 UTC, chrisohaver commented on migration/plugins.go
> +				"Fall": {},
```suggestion
				"fallthrough": {}, // new option
```

2023-08-18 13:28 UTC, chrisohaver commented on migration/plugins.go
> +				"ttl":         {}, // new option
```suggestion
				"ttl":         {},
```

2023-08-18 13:28 UTC, chrisohaver commented on migration/versions.go
> +	"rewrite":      plugins["rewrite"]["v3"],
```suggestion
	"rewrite":      plugins["rewrite"]["v3"], // add cname_target option
```

2023-08-18 13:31 UTC, chrisohaver requested changes
There was also a new option added to the cache plugin: `keepttl` https://github.com/coredns/coredns/pull/5879

2023-08-21 01:04 UTC, tukwila commented
> ~There was also a new option added to the cache plugin: `keepttl` [coredns/coredns#5879](https://github.com/coredns/coredns/pull/5879)~
> 
> Nevermind - that was added in 1.10.1 ...
> 
> ... Although it looks like it's missing from the 1.10.1 migration. Eventually that should be fixed, but OK if you don't want to do it in this PR.

yes，i review coredns v1.10.1 releasenotes and append cache plugin new added option keepttl. Please review it. -:)

2023-08-22 00:44 UTC, tukwila commented
@chrisohaver Could you review my commit again? i hope my commit is within your expected. :)

2023-08-22 12:04 UTC, chrisohaver requested changes
Looks good! Thanks!  Just one fix required to the name of the new `fallthrough` option in _k8s_external_.

2023-08-22 12:04 UTC, chrisohaver commented on migration/plugins.go
> +				"Fall": {}, // new option
```suggestion
				"fallthtrough": {}, // new option
```

2023-08-22 12:06 UTC, chrisohaver commented on corefile-tool/cmd/validversions_test.go
> +1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.9, 1.7.0, 1.7.1, 1.8.0, 1.8.3, 1.8
```suggestion
1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.9, 1.7.0, 1.7.1, 1.8.0, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.10.0, 1.10.1, 1.11.0
```

2023-08-22 13:57 UTC, tukwila commented
> ... and also fix to version string in valid versions test.

@chrisohaver yes, it's my fault and I corrected. I hope you are online now then review it again. Cross my finger to pray that it can be ok this time.

2023-08-22 13:59 UTC, chrisohaver approved these changes

2023-08-22 14:09 UTC, merged